#!/usr/bin/env node

/**
 * Step 3: Execute AI Decisions
 *
 * This script:
 * 1. Reads the decisions file generated by Claude
 * 2. Logs into Xero
 * 3. Navigates to reconciliation screen
 * 4. Executes each decision via Puppeteer
 * 5. Generates execution report
 */

const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');
const XeroAuth = require('./xero-auth');
const fs = require('fs').promises;
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../../.env') });

puppeteer.use(StealthPlugin());

class DecisionExecutor {
  constructor(decisionsFile) {
    this.browser = null;
    this.page = null;
    this.logsDir = path.join(__dirname, 'logs');
    this.decisionsFile = decisionsFile;
    this.results = [];
    this.errors = [];
  }

  async init() {
    console.log('⚙️  Xero Decision Executor');
    console.log('='.repeat(80));
    console.log('');

    // Load decisions
    const data = await fs.readFile(this.decisionsFile, 'utf8');
    this.decisions = JSON.parse(data);

    console.log(`📋 Loaded decisions for ${this.decisions.month.toUpperCase()} ${this.decisions.year}`);
    console.log(`   Total decisions: ${this.decisions.decisions.length}`);
    console.log('');

    await fs.mkdir(this.logsDir, { recursive: true });

    this.browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-blink-features=AutomationControlled'
      ]
    });

    this.page = await this.browser.newPage();
    await this.page.setViewport({ width: 1920, height: 1080 });

    console.log('✓ Browser initialized');
    console.log('');
  }

  async login() {
    const auth = new XeroAuth(this.page, this.logsDir);
    await auth.login();
  }

  async navigateToReconciliation() {
    console.log('🏦 Navigating to Bank Reconciliation...');
    await new Promise(resolve => setTimeout(resolve, 5000));

    const reconcileButtonSelector = 'a[data-automationid="reconcileBankItems"]';
    await this.page.waitForSelector(reconcileButtonSelector, { timeout: 10000 });
    await this.page.click(reconcileButtonSelector);

    await this.page.waitForNavigation({
      waitUntil: 'networkidle2',
      timeout: 30000
    });

    await new Promise(resolve => setTimeout(resolve, 3000));
    console.log('✓ Reconciliation screen loaded');
    console.log('');
  }

  async executeDecision(decision) {
    const { transaction, action, contact, accountCode, accountName, category, description, reason } = decision;

    console.log(`  💰 ${transaction.description.substring(0, 40)}...`);
    console.log(`     Action: ${action}`);

    if (action === 'SKIP' || action === 'EXCLUDE') {
      console.log(`     Reason: ${reason}`);
      console.log(`     ⏭️  Skipping`);
      console.log('');
      return { success: true, skipped: true };
    }

    if (action !== 'CREATE') {
      console.log(`     ⚠️  Unknown action: ${action}`);
      console.log('');
      return { success: false, error: `Unknown action: ${action}` };
    }

    console.log(`     Contact: ${contact}`);
    console.log(`     Account: ${accountCode} - ${accountName}`);
    console.log(`     Category: ${category || 'N/A'}`);

    const lineSelector = `#statementLines .line[data-id="${transaction.dataId}"]`;

    try {
      // Click Create tab
      const createTabSelector = `${lineSelector} .tabs a.t2`;
      await this.page.waitForSelector(createTabSelector, { timeout: 5000 });
      await this.page.click(createTabSelector);
      await new Promise(resolve => setTimeout(resolve, 1000));

      // Check if Xero has a suggestion (pre-filled fields)
      if (transaction.xeroSuggestion && transaction.xeroSuggestion.hasSuggestion) {
        console.log(`     💡 Xero Create Suggestion detected`);
        console.log(`        Xero Contact: ${transaction.xeroSuggestion.contact || 'N/A'}`);
        console.log(`        Xero Account: ${transaction.xeroSuggestion.account || 'N/A'}`);
        console.log(`        AI   Contact: ${contact}`);
        console.log(`        AI   Account: ${accountCode} - ${accountName}`);

        // Validate Xero suggestion against AI decision
        const xeroContactMatches = transaction.xeroSuggestion.contact === contact;
        const xeroAccountMatches = transaction.xeroSuggestion.account &&
                                  transaction.xeroSuggestion.account.includes(accountCode);

        if (xeroContactMatches && xeroAccountMatches) {
          console.log(`     ✅ Xero suggestion Contact & Account match - keeping those`);
          console.log(`     📝 BUT overriding Description with actual bank statement text`);

          // CRITICAL: Always override description with actual bank statement description
          // Xero's suggested description is often from old transactions
          const descriptionSelector = `${lineSelector} .info.c2 input[placeholder="Enter a description..."]`;
          await this.page.waitForSelector(descriptionSelector, { timeout: 5000 });
          await this.page.click(descriptionSelector, { clickCount: 3 });
          await this.page.keyboard.press('Backspace');
          await this.page.type(descriptionSelector, description, { delay: 50 });

          // Blur the description field
          await this.page.evaluate((selector) => {
            const field = document.querySelector(selector);
            if (field) field.blur();
          }, descriptionSelector);
          await new Promise(resolve => setTimeout(resolve, 500));

          await new Promise(resolve => setTimeout(resolve, 2000));
        } else if (xeroContactMatches && !xeroAccountMatches) {
          console.log(`     ✅ Xero suggestion Contact matches - keeping it`);
          console.log(`     ⚠️  Xero suggestion Account is WRONG - overriding with AI decision`);
          console.log(`     📝 Overriding Description with actual bank statement text`);

          // Keep contact (don't touch it), but override Account and Description

          // Override Account
          const accountSelector = `${lineSelector} .info.c2 input[placeholder="Choose the account..."]`;
          await this.page.waitForSelector(accountSelector, { timeout: 5000 });
          await this.page.click(accountSelector, { clickCount: 3 });
          await this.page.keyboard.press('Backspace');
          await this.page.type(accountSelector, accountName, { delay: 100 });
          await new Promise(resolve => setTimeout(resolve, 2000));
          await this.page.keyboard.press('ArrowDown');
          await this.page.keyboard.press('Enter');
          await new Promise(resolve => setTimeout(resolve, 1000));

          // Fill Category if needed
          if (category && category !== 'Revenue') {
            try {
              const costsSelector = `${lineSelector} input[title="Costs"]`;
              const costsFieldExists = await this.page.$(costsSelector);
              if (costsFieldExists) {
                await this.page.click(costsSelector, { clickCount: 3 });
                await this.page.keyboard.press('Backspace');
                await this.page.type(costsSelector, category, { delay: 100 });
                await new Promise(resolve => setTimeout(resolve, 2000));
                await this.page.keyboard.press('ArrowDown');
                await this.page.keyboard.press('Enter');
                await new Promise(resolve => setTimeout(resolve, 1000));
              }
            } catch (error) {
              console.log(`     ℹ️  Category field not found (may be auto-set)`);
            }
          }

          // Override Description
          const descriptionSelector = `${lineSelector} .info.c2 input[placeholder="Enter a description..."]`;
          await this.page.waitForSelector(descriptionSelector, { timeout: 5000 });
          await this.page.click(descriptionSelector, { clickCount: 3 });
          await this.page.keyboard.press('Backspace');
          await this.page.type(descriptionSelector, description, { delay: 50 });

          // Blur the description field
          await this.page.evaluate((selector) => {
            const field = document.querySelector(selector);
            if (field) field.blur();
          }, descriptionSelector);
          await new Promise(resolve => setTimeout(resolve, 500));

          await new Promise(resolve => setTimeout(resolve, 3000));
        } else {
          console.log(`     ⚠️  Xero suggestion does NOT match AI decision`);
          console.log(`        Contact match: ${xeroContactMatches}`);
          console.log(`        Account match: ${xeroAccountMatches}`);
          console.log(`     🔧 Overriding with AI decision...`);

          // Clear and override with AI decision
          // We need to manually fill the fields with our AI decision
          const contactSelector = `${lineSelector} .info.c2 input[placeholder="Name of the contact..."]`;
          await this.page.waitForSelector(contactSelector, { timeout: 5000 });

          // Clear existing value
          await this.page.click(contactSelector, { clickCount: 3 });
          await this.page.keyboard.press('Backspace');

          // Type our contact
          await this.page.type(contactSelector, contact, { delay: 100 });
          await new Promise(resolve => setTimeout(resolve, 2000));
          await this.page.keyboard.press('ArrowDown');
          await this.page.keyboard.press('Enter');
          await new Promise(resolve => setTimeout(resolve, 1000));

          // Clear and fill Account
          const accountSelector = `${lineSelector} .info.c2 input[placeholder="Choose the account..."]`;
          await this.page.waitForSelector(accountSelector, { timeout: 5000 });
          await this.page.click(accountSelector, { clickCount: 3 });
          await this.page.keyboard.press('Backspace');
          await this.page.type(accountSelector, accountName, { delay: 100 });
          await new Promise(resolve => setTimeout(resolve, 2000));
          await this.page.keyboard.press('ArrowDown');
          await this.page.keyboard.press('Enter');
          await new Promise(resolve => setTimeout(resolve, 1000));

          // Fill Category if needed
          if (category && category !== 'Revenue') {
            try {
              const costsSelector = `${lineSelector} input[title="Costs"]`;
              const costsFieldExists = await this.page.$(costsSelector);
              if (costsFieldExists) {
                await this.page.click(costsSelector, { clickCount: 3 });
                await this.page.keyboard.press('Backspace');
                await this.page.type(costsSelector, category, { delay: 100 });
                await new Promise(resolve => setTimeout(resolve, 2000));
                await this.page.keyboard.press('ArrowDown');
                await this.page.keyboard.press('Enter');
                await new Promise(resolve => setTimeout(resolve, 1000));
              }
            } catch (error) {
              console.log(`     ℹ️  Category field not found (may be auto-set)`);
            }
          }

          // Fill Description
          const descriptionSelector = `${lineSelector} .info.c2 input[placeholder="Enter a description..."]`;
          await this.page.waitForSelector(descriptionSelector, { timeout: 5000 });
          await this.page.click(descriptionSelector, { clickCount: 3 });
          await this.page.keyboard.press('Backspace');
          await this.page.type(descriptionSelector, description, { delay: 50 });

          // Blur the description field
          await this.page.evaluate((selector) => {
            const field = document.querySelector(selector);
            if (field) field.blur();
          }, descriptionSelector);
          await new Promise(resolve => setTimeout(resolve, 500));

          await new Promise(resolve => setTimeout(resolve, 3000));
        }

        // Now wait for OK button (whether we used suggestion or overrode it)
        await new Promise(resolve => setTimeout(resolve, 2000));

        const okButtonSelector = `${lineSelector} .ok a.okayButton`;

        // Wait for OK button to appear and be enabled
        await this.page.waitForFunction(
          (selector) => {
            const button = document.querySelector(selector);
            return button && button.offsetParent !== null && !button.classList.contains('disabled');
          },
          { timeout: 15000 },
          okButtonSelector
        );

        // Additional wait
        await new Promise(resolve => setTimeout(resolve, 1000));

        // Click OK button
        const clicked = await this.page.evaluate((selector) => {
          const button = document.querySelector(selector);
          if (button && !button.classList.contains('disabled')) {
            button.click();
            return true;
          }
          return false;
        }, okButtonSelector);

        if (!clicked) {
          throw new Error('Could not click OK button - button was disabled or not found');
        }

        console.log(`     🖱️  Clicked OK button`);

        // Wait for save to complete and line to disappear
        await new Promise(resolve => setTimeout(resolve, 2000));

        // Verify the transaction line disappeared
        const lineStillExists = await this.page.$(lineSelector);
        if (lineStillExists) {
          const timestamp = Date.now();
          const screenshotPath = path.join(this.logsDir, `still-exists-${timestamp}.png`);
          await this.page.screenshot({ path: screenshotPath, fullPage: true });
          console.log(`     ⚠️  Transaction still visible after OK click`);
          console.log(`     📸 Screenshot: ${screenshotPath}`);
          return { success: false, error: 'Transaction did not disappear after OK click' };
        }

        console.log(`     ✅ Reconciled successfully`);
        console.log('');
        return { success: true };
      }

      // No Xero suggestion - manually fill fields
      console.log(`     📝 Manually filling fields (no Xero suggestion)`);

      // Fill Contact
      const contactSelector = `${lineSelector} .info.c2 input[placeholder="Name of the contact..."]`;
      await this.page.waitForSelector(contactSelector, { timeout: 5000 });
      await this.page.click(contactSelector);
      await this.page.type(contactSelector, contact, { delay: 100 });
      await new Promise(resolve => setTimeout(resolve, 2000)); // Increased wait for dropdown
      await this.page.keyboard.press('ArrowDown');
      await this.page.keyboard.press('Enter');
      await new Promise(resolve => setTimeout(resolve, 1000)); // Wait for selection to register

      // Fill Account - use full account name to avoid wrong selection
      const accountSelector = `${lineSelector} .info.c2 input[placeholder="Choose the account..."]`;
      await this.page.waitForSelector(accountSelector, { timeout: 5000 });
      await this.page.click(accountSelector);
      await this.page.type(accountSelector, accountName, { delay: 100 });
      await new Promise(resolve => setTimeout(resolve, 2000)); // Increased wait for dropdown
      await this.page.keyboard.press('ArrowDown');
      await this.page.keyboard.press('Enter');
      await new Promise(resolve => setTimeout(resolve, 1000)); // Wait for selection to register

      // Fill Category (if not Revenue)
      if (category && category !== 'Revenue') {
        try {
          const costsSelector = `${lineSelector} input[title="Costs"]`;
          const costsFieldExists = await this.page.$(costsSelector);

          if (costsFieldExists) {
            await this.page.waitForSelector(costsSelector, { timeout: 5000 });
            await this.page.click(costsSelector);
            await this.page.type(costsSelector, category, { delay: 100 });
            await new Promise(resolve => setTimeout(resolve, 2000)); // Increased wait
            await this.page.keyboard.press('ArrowDown');
            await this.page.keyboard.press('Enter');
            await new Promise(resolve => setTimeout(resolve, 1000)); // Wait for selection
          }
        } catch (error) {
          console.log(`     ℹ️  Category field not found (may be auto-set)`);
        }
      }

      // Fill Description
      const descriptionSelector = `${lineSelector} .info.c2 input[placeholder="Enter a description..."]`;
      await this.page.waitForSelector(descriptionSelector, { timeout: 5000 });
      await this.page.click(descriptionSelector);
      await this.page.type(descriptionSelector, description, { delay: 50 });

      // CRITICAL: Blur the description field so Xero validates and commits the value
      await this.page.evaluate((selector) => {
        const field = document.querySelector(selector);
        if (field) field.blur();
      }, descriptionSelector);
      await new Promise(resolve => setTimeout(resolve, 500)); // Wait for blur to process

      // After filling all required fields (Contact, Account, Category, Description),
      // the OK button should now appear. Wait longer for Xero to enable it.
      await new Promise(resolve => setTimeout(resolve, 3000)); // Increased from 1s to 3s

      const okButtonSelector = `${lineSelector} .ok a.okayButton`;

      // Wait for OK button to appear and be enabled
      await this.page.waitForFunction(
        (selector) => {
          const button = document.querySelector(selector);
          return button && button.offsetParent !== null && !button.classList.contains('disabled');
        },
        { timeout: 15000 }, // Increased timeout
        okButtonSelector
      );

      // Additional wait to ensure button is fully ready
      await new Promise(resolve => setTimeout(resolve, 1000));

      // Try to click OK button - use evaluate to ensure it actually clicks
      const clicked = await this.page.evaluate((selector) => {
        const button = document.querySelector(selector);
        if (button && !button.classList.contains('disabled')) {
          button.click();
          return true;
        }
        return false;
      }, okButtonSelector);

      if (!clicked) {
        throw new Error('Could not click OK button - button was disabled or not found');
      }

      console.log(`     🖱️  Clicked OK button`);

      // Wait for save to complete and line to disappear
      await new Promise(resolve => setTimeout(resolve, 2000));

      // Verify the transaction line disappeared (indicating successful reconciliation)
      const lineStillExists = await this.page.$(lineSelector);
      if (lineStillExists) {
        // Take screenshot if line still exists
        const timestamp = Date.now();
        const screenshotPath = path.join(this.logsDir, `still-exists-${timestamp}.png`);
        await this.page.screenshot({ path: screenshotPath, fullPage: true });
        console.log(`     ⚠️  Transaction still visible after OK click`);
        console.log(`     📸 Screenshot: ${screenshotPath}`);
        return { success: false, error: 'Transaction did not disappear after OK click' };
      }

      console.log(`     ✅ Reconciled successfully (line disappeared)`);
      console.log('');

      return { success: true };

    } catch (error) {
      console.log(`     ❌ Error: ${error.message}`);

      // Save error screenshot
      const timestamp = Date.now();
      const screenshotPath = path.join(this.logsDir, `error-${timestamp}.png`);
      try {
        await this.page.screenshot({ path: screenshotPath, fullPage: true });
        console.log(`     📸 Error screenshot: ${screenshotPath}`);
      } catch (screenshotError) {
        console.log(`     ⚠️  Could not save screenshot: ${screenshotError.message}`);
      }

      console.log('');
      return { success: false, error: error.message };
    }
  }

  async executeAll() {
    console.log('🤖 Executing AI decisions...');
    console.log('='.repeat(80));
    console.log('');

    for (let i = 0; i < this.decisions.decisions.length; i++) {
      const decision = this.decisions.decisions[i];

      console.log(`[${i + 1}/${this.decisions.decisions.length}] ${decision.transaction.date} | ${decision.transaction.type} | €${decision.transaction.amount}`);

      const result = await this.executeDecision(decision);

      this.results.push({
        transaction: decision.transaction,
        decision: decision,
        result: result
      });

      if (!result.success) {
        this.errors.push({
          transaction: decision.transaction,
          decision: decision,
          error: result.error
        });
      }

      // Pause between reconciliations
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
  }

  generateReport() {
    console.log('');
    console.log('='.repeat(80));
    console.log('📊 EXECUTION REPORT');
    console.log('='.repeat(80));
    console.log('');

    const successful = this.results.filter(r => r.result.success && !r.result.skipped);
    const skipped = this.results.filter(r => r.result.skipped);
    const errors = this.results.filter(r => !r.result.success);

    console.log(`✅ Successfully Executed: ${successful.length}`);
    console.log(`⏭️  Skipped: ${skipped.length}`);
    console.log(`❌ Errors: ${errors.length}`);
    console.log('');

    if (errors.length > 0) {
      console.log('❌ ERRORS:');
      errors.forEach((err, idx) => {
        console.log(`  ${idx + 1}. ${err.transaction.description}`);
        console.log(`     Error: ${err.error}`);
      });
      console.log('');
    }

    console.log('='.repeat(80));
  }

  async close() {
    if (this.browser) {
      await this.browser.close();
      console.log('🔒 Browser closed');
    }
  }

  async run() {
    try {
      await this.init();
      await this.login();
      await this.navigateToReconciliation();
      await this.executeAll();
      this.generateReport();

    } catch (error) {
      console.error('');
      console.error('❌ Error:', error.message);
      console.error('');

      if (this.page) {
        const errorScreenshot = path.join(this.logsDir, `error-${Date.now()}.png`);
        await this.page.screenshot({ path: errorScreenshot, fullPage: true });
        console.error(`📸 Error screenshot: ${errorScreenshot}`);
      }

      throw error;
    } finally {
      await this.close();
    }
  }
}

// Parse command line argument
const decisionsFile = process.argv[2];

if (!decisionsFile) {
  console.error('Usage: node execute-recon.js <decisions-file.json>');
  process.exit(1);
}

// Run the executor
const executor = new DecisionExecutor(decisionsFile);
executor.run()
  .then(() => {
    console.log('✓ Execution complete');
    process.exit(0);
  })
  .catch((error) => {
    console.error('✗ Failed:', error.message);
    process.exit(1);
  });
